updated main.tf - with needs to generate values for public_ip_name an…
cloud-native-toolkit/terraform-azure-vpn-gateway pull request #6
Opened 2022-07-20 11:28 UTC by sunmeher

…d vpn_ip_configuration_name

Signed-off-by: sunmeher <45628173+sunmeher@users.noreply.github.com>

2022-08-08 13:07 UTC, sunmeher commented
@rich-ehrhardt we have integrate the VPN Gateway related subnet creation with this module. please validate and update.

2022-08-09 04:24 UTC, rich-ehrhardt requested changes
Looks good. Please update the readme before final merge.

2022-08-09 08:19 UTC, sunmeher commented
@rich-ehrhardt updated the README.md file. please check and update. Thank you

2022-08-10 06:43 UTC, rich-ehrhardt approved these changes

2022-08-10 06:43 UTC, merged